### ISSUE TITLE
BUG: Deltroid claims .md files

### ISSUE THREAD

**Issue by LitRitt** [lonkelle/Deltroid#12]
Deltroid claims the .md extension for mega drive games, which leads to other apps being unable to open them. .md is the common extension for markdown files, and should never be claimed in this way.
![572A3D0A-B062-4BED-BD69-ED590C3BDEEC](https://user-images.githubusercontent.com/78584620/212728668-7b335f19-4ec7-4d0b-9d10-df6d5d9172a2.jpeg)

**Comment by LitRitt** [comment]
Code Reference
https://github.com/lonkelle/Deltroid/blob/c793b1b42db169a167c9817241f60e1f0f918a8d/Delta/Supporting%20Files/Info.plist#L397

**Comment by LitRitt** [comment]
Is there some way to let Deltroid open .md files without claiming them as a proprietary file extension?

**Comment by LitRitt** [comment]
Relevant Apple Docs
https://developer.apple.com/documentation/uniformtypeidentifiers/defining_file_and_data_types_for_your_app

**Comment by LitRitt** [comment]
Relevant Doc
https://coderwall.com/p/83djxa/registering-your-app-to-be-able-to-open-images-from-other-apps

**Comment by lonkelle** [comment]
Fixed with this commit: https://github.com/lonkelle/Deltroid/commit/0e5916427837eba26c0872b30bfe7bfb76b60441. Deltroid was actually owning **all** file types when it should share with all other emus.

**Comment by lonkelle** [comment]
Fixed in develop branch as well: https://github.com/lonkelle/Deltroid/commit/e8008b6f5c1097e13a381d7e2141147b51449e43.  I honestly need to trim all these branches down to just main.
