### ISSUE TITLE
QOL: Add a toggle for audio muting based on the silent switch

### ISSUE THREAD

**Issue by lonkelle** [lonkelle/Deltroid#2]
Hey @TimOliver, wasn't sure how you wanted to implement this so just throwing this out there as an idea. I'm sure there's a better way but I wanted to at least have a mock up for the next enhancement.

![image jpeg](https://user-images.githubusercontent.com/5572600/209824246-7fef572c-d37a-41f2-95a3-836acf2c5a44.jpg)

**Comment by TimOliver** [comment]
Woah! Yeah? Interesting! I hadn't even thought about music. At the moment, I just changed the AudioManager to ignore the mute switch when headphones are plugged in. It seemed like the appropriate system-level behaviour on iOS. But yeah, music will play over the top of it, which sounds really muddy.

I wonder if it's worth adding another section to the Settings screen to enable better customisability. So, giving users the choice between cancelling all other audio to give Deltroid priority, or conversely, duck Deltroid so you can have your own music over the top.

**Comment by lonkelle** [comment]
In my personal opinion and from the, at least, 37 (made up number) requests for this feature of the past 3.5 years (with basically only two use cases), I think customization is important. Tho ignoring the mute switch with headphones plugged in is an improvement either way.

But digging into this, my thought is - a new setting in Settings labeled "Mute Switch Behavior" - which, by default, the state is: 

• State 1 (Default): "Silence Delta, does not pause music" (if headphones are plugged in, the opposite happens, it pauses music but does not silence Delta)
• State 2: "Does not silence Delta, does pause music" (if headphones are plugged in, the opposite happens, it doesn't pause music but does silence Delta.

Nowww, the UI telling the user's those two options is tricky in my head. Do you have an idea for a UI that could convey the options? It's not like we can't use two switches like the mockup has but there's only two states so the second switch would just be there for conveyance. 

Really scratching my head on this one tbh. :P

**Comment by lonkelle** [comment]
@ianclawson In this issue - do my "two states" proposal make sense? I'm just having a hard time seeing the UI to convey both states. Maybe a little description under the switch that changes depending on what side the toggle is on. 🤔

**Comment by ianclawson** [comment]
@lonkelle great question here 🤔 I'll admit this is a bit hard for me to wrap my head around as well.

I tried something very close to this once before in my more 'experimental' private Delta fork. There I eventually landed on the approach in the following screenshot: a Toggle determines if the Mute switch should be applied to Delta's audio, and then a Master Volume slider.

I felt like this added some clarity, with the added benefit of allowing the user to more gradually control the app volume.

Thoughts?

![IMG_08734AD59AFA-1](https://user-images.githubusercontent.com/18663382/212237705-8ebb09a5-e073-4128-996d-b596227fc002.jpeg)

**Comment by lonkelle** [comment]
@ianclawson This is actually better than the two states given users will be able to mix volume between game and their music app. This is def the way to go.

**Comment by ianclawson** [comment]
@lonkelle if you'd like, I can take a look at adding this once the other PRs are finished. I still have the code so it should be straightforward.

**Comment by lonkelle** [comment]
You're my hero; def do that. Def excited to launch this alongside SideStore (which has my current focus)! I owe ya. ❤️
